kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "{}"
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        hosts {
          ${CONTOUR_CLUSTER_IP} core.harbor.domain
          ${CONTOUR_CLUSTER_IP} notary.harbor.domain
          ${CONTOUR_CLUSTER_IP} core.h1.harbor.domain
          ${CONTOUR_CLUSTER_IP} notary.h1.harbor.domain
          ${CONTOUR_CLUSTER_IP} core.h2.harbor.domain
          ${CONTOUR_CLUSTER_IP} notary.h2.harbor.domain

          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
