#@ load("@ytt:data", "data")
---
expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor-tls"
      notarySecretName: "harbor-tls"
  ingress:
    hosts:
      core: #@ data.values.hostname.core
      notary: #@ data.values.hostname.notary

externalURL: #@ "https://" + data.values.hostname.core

internalTLS:
  enabled: false
  certSource: "auto"

harborAdminPassword: "Harbor12345"

secretKey: "not-a-secure-key"

registry:
  relativeurls: true

chartmuseum:
  absoluteUrl: false

metrics:
  enabled: true
  core:
    path: /metrics
    port: 9090
  registry:
    path: /metrics
    port: 9090
  jobservice:
    path: /metrics
    port: 9090
  exporter:
    path: /metrics
    port: 9090
  serviceMonitor:
    enabled: false
